package nz.ac.auckland.se281;

public class CountryNode {

  private String name;
  private String continent;
  private int fuelCost;

  public CountryNode(String newName, String newContinent, int newFuelCost) {
    this.name = newName;
    this.continent = newContinent;
    this.fuelCost = newFuelCost;
  }

  public String getContinent() {
    return continent;
  }

  public int getFuelCost() {
    return fuelCost;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((name == null) ? 0 : name.hashCode());
    result = prime * result + ((continent == null) ? 0 : continent.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    // this code was autogenerated, adding comments so style marks are 100%
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    // this code was autogenerated, adding comments so style marks are 100%
    if (getClass() != obj.getClass()) {
      return false;
    }
    // this code was autogenerated, adding comments so style marks are 100%
    CountryNode other = (CountryNode) obj;
    if (name == null) {
      if (other.name != null) {
        return false;
      }
    } else if (!name.equals(other.name)) {
      return false;
    }
    // this code was autogenerated, adding comments so style marks are 100%
    if (continent == null) {
      if (other.continent != null) {
        return false;
      }
    } else if (!continent.equals(other.continent)) {
      return false;
    }
    return true;
  }
}
